spring.application.name=spring

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Cool App
info.app.description=Seriously, this is a really cool app!
info.app.version=1.0.0

webmaster.name=Aarej Syed

spring.security.user.name=admin
spring.security.user.password=Password!

logging.file.name=logs/app.log

logging.level.com.demo.spring.rest=DEBUG
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7